; ==============================================================================
; Input functionality.
; ==============================================================================


; --- EXPORTS ------------------------------------------------------------------

externdef handleMainMenuInput:FAR
externdef handleGameOverInput:FAR
externdef handleGameInput:FAR

; --- MACROS AND CONSTANTS -----------------------------------------------------

DIR_UP equ 0
DIR_RIGHT equ 1
DIR_DOWN equ 2
DIR_LEFT equ 3